### ISSUE TITLE
Leaves Original (empty) Meta Tags

### ISSUE THREAD

**Issue by AndyPeterson** [stevewithington/MuraMetaGenerator#2]
Hi Steve,

After installing this plugin to a site, I noticed that, while the keywords and description meta tags are generated, the original, blank meta tags are left, leaving two keyword and description tags each: 

If I do remove these tags from the html_head.cfm tag of mura's merced theme, the issue goes away. I'm on Mura 6.1.6 and version 1.0.4 of the MuraMetaGenerator, which is the version on GitHub from what I can tell.

Here's a graphic showing the issue. Please let me know how I can help.

http://content.screencast.com/users/Literal6/folders/Jing/media/5d939b3d-8b7c-4ba4-81d9-9d6455f9684d/2015-01-23_1546.png

**Comment by markrely** [comment]
Nice catch!  Who populated the keywords table?  What is sxlnbsp mean?

**Comment by stevewithington** [comment]
@AndyPeterson, sorry for the delay on working on this ... been a bit busy with the new release of Mura. anyway, i've pushed a new release to address this. also, i'm working on adding some more functionality into this ... this is one of my oldest plugins! didn't realize people were still using it.

i should point out that you should just delete the existing plugin, and then install the new one.

cheers,
steve
